future: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
github: ESO-Wine-And-Cheese
url: https://eso-wine-and-cheese.github.io/
name: ESO Wine & Cheese 
description: ESO W&C schedule page
twitter: yourtwitterhandle
calendar: https://yourcalendarurl
mailinglist: https://yourmailinglisturl
gravatar_url: 
disqus_username:
